<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<script type="application/json" id="data">
    {
        "nodes": [{
            "label": "adaptationism",
            "id": 1,
            "Betweenness": 195.14932102059493,
            "Out-Degree": 12,
            "Degree": 19,
            "In-Degree": 7,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.7037037037037037,
            "size": 10.0
        }, {
            "label": "altruism-biological",
            "id": 2,
            "Betweenness": 4.272222222222222,
            "Out-Degree": 2,
            "Degree": 8,
            "In-Degree": 6,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.7160493827160495,
            "size": 10.0
        }, {
            "label": "bell-theorem",
            "id": 3,
            "Betweenness": 19.75913464044269,
            "Out-Degree": 4,
            "Degree": 14,
            "In-Degree": 10,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.0246913580246915,
            "size": 10.0
        }, {
            "label": "biodiversity",
            "id": 4,
            "Betweenness": 6.844302124890359,
            "Out-Degree": 1,
            "Degree": 5,
            "In-Degree": 4,
            "Eccentricity": 6.0,
            "group": 0,
            "Closeness": 4.320987654320987,
            "size": 10.0
        }, {
            "label": "biology-individual",
            "id": 5,
            "Betweenness": 310.32284075573546,
            "Out-Degree": 12,
            "Degree": 17,
            "In-Degree": 5,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.6790123456790123,
            "size": 10.0
        }, {
            "label": "biology-philosophy",
            "id": 6,
            "Betweenness": 1459.372966147363,
            "Out-Degree": 31,
            "Degree": 46,
            "In-Degree": 15,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.234567901234568,
            "size": 10.0
        }, {
            "label": "biology-self",
            "id": 7,
            "Betweenness": 19.136580086580086,
            "Out-Degree": 2,
            "Degree": 6,
            "In-Degree": 4,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.2098765432098766,
            "size": 10.0
        }, {
            "label": "bohr-correspondence",
            "id": 8,
            "Betweenness": 0.0,
            "Out-Degree": 5,
            "Degree": 5,
            "In-Degree": 0,
            "Eccentricity": 6.0,
            "group": 3,
            "Closeness": 3.5121951219512195,
            "size": 10.0
        }, {
            "label": "causation-mani",
            "id": 9,
            "Betweenness": 92.8812192936872,
            "Out-Degree": 1,
            "Degree": 5,
            "In-Degree": 4,
            "Eccentricity": 9.0,
            "group": 1,
            "Closeness": 5.209876543209877,
            "size": 10.0
        }, {
            "label": "causation-probabilistic",
            "id": 10,
            "Betweenness": 843.5183597785008,
            "Out-Degree": 9,
            "Degree": 15,
            "In-Degree": 6,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.222222222222222,
            "size": 10.0
        }, {
            "label": "chance-randomness",
            "id": 11,
            "Betweenness": 0.0,
            "Out-Degree": 5,
            "Degree": 5,
            "In-Degree": 0,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 4.0120481927710845,
            "size": 10.0
        }, {
            "label": "chaos",
            "id": 12,
            "Betweenness": 22.393070818070818,
            "Out-Degree": 6,
            "Degree": 8,
            "In-Degree": 2,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.2682926829268295,
            "size": 10.0
        }, {
            "label": "chemistry",
            "id": 13,
            "Betweenness": 35.29089979385598,
            "Out-Degree": 5,
            "Degree": 6,
            "In-Degree": 1,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.925925925925926,
            "size": 10.0
        }, {
            "label": "conservation-biology",
            "id": 14,
            "Betweenness": 0.5,
            "Out-Degree": 3,
            "Degree": 5,
            "In-Degree": 2,
            "Eccentricity": 7.0,
            "group": 0,
            "Closeness": 4.0,
            "size": 10.0
        }, {
            "label": "creationism",
            "id": 15,
            "Betweenness": 0.0,
            "Out-Degree": 2,
            "Degree": 5,
            "In-Degree": 3,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.6790123456790123,
            "size": 10.0
        }, {
            "label": "darwinism",
            "id": 16,
            "Betweenness": 184.7668626787579,
            "Out-Degree": 9,
            "Degree": 19,
            "In-Degree": 10,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.7037037037037037,
            "size": 10.0
        }, {
            "label": "determinism-causal",
            "id": 17,
            "Betweenness": 596.6870486126224,
            "Out-Degree": 6,
            "Degree": 12,
            "In-Degree": 6,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 3.8641975308641974,
            "size": 10.0
        }, {
            "label": "ecology",
            "id": 18,
            "Betweenness": 53.53901451489686,
            "Out-Degree": 4,
            "Degree": 6,
            "In-Degree": 2,
            "Eccentricity": 6.0,
            "group": 0,
            "Closeness": 3.0987654320987654,
            "size": 10.0
        }, {
            "label": "einstein-philscience",
            "id": 19,
            "Betweenness": 988.8197954895189,
            "Out-Degree": 12,
            "Degree": 23,
            "In-Degree": 11,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.222222222222222,
            "size": 10.0
        }, {
            "label": "epigenesis",
            "id": 20,
            "Betweenness": 32.58096159145644,
            "Out-Degree": 4,
            "Degree": 8,
            "In-Degree": 4,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.037037037037037,
            "size": 10.0
        }, {
            "label": "epistemology-evolutionary",
            "id": 21,
            "Betweenness": 1.503113553113553,
            "Out-Degree": 2,
            "Degree": 3,
            "In-Degree": 1,
            "Eccentricity": 7.0,
            "group": 1,
            "Closeness": 4.1234567901234565,
            "size": 10.0
        }, {
            "label": "epistemology-geometry",
            "id": 22,
            "Betweenness": 0.0,
            "Out-Degree": 3,
            "Degree": 3,
            "In-Degree": 0,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.5058823529411764,
            "size": 10.0
        }, {
            "label": "equivME",
            "id": 23,
            "Betweenness": 0.5,
            "Out-Degree": 2,
            "Degree": 4,
            "In-Degree": 2,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.197530864197531,
            "size": 10.0
        }, {
            "label": "ergodic-hierarchy",
            "id": 24,
            "Betweenness": 0.0,
            "Out-Degree": 1,
            "Degree": 1,
            "In-Degree": 0,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 4.829268292682927,
            "size": 10.0
        }, {
            "label": "ernst-mach",
            "id": 25,
            "Betweenness": 824.0725016766902,
            "Out-Degree": 4,
            "Degree": 20,
            "In-Degree": 16,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.037037037037037,
            "size": 10.0
        }, {
            "label": "evolutionary-genetics",
            "id": 26,
            "Betweenness": 39.530538231449974,
            "Out-Degree": 2,
            "Degree": 12,
            "In-Degree": 10,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.802469135802469,
            "size": 10.0
        }, {
            "label": "evolutionary-psychology",
            "id": 27,
            "Betweenness": 27.43625991196573,
            "Out-Degree": 2,
            "Degree": 7,
            "In-Degree": 5,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.185185185185185,
            "size": 10.0
        }, {
            "label": "evolution-cultural",
            "id": 28,
            "Betweenness": 250.75847065235422,
            "Out-Degree": 7,
            "Degree": 12,
            "In-Degree": 5,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.962962962962963,
            "size": 10.0
        }, {
            "label": "evolution-to-1872",
            "id": 29,
            "Betweenness": 0.0,
            "Out-Degree": 13,
            "Degree": 13,
            "In-Degree": 0,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.682926829268293,
            "size": 10.0
        }, {
            "label": "fitness",
            "id": 30,
            "Betweenness": 161.552538428802,
            "Out-Degree": 8,
            "Degree": 12,
            "In-Degree": 4,
            "Eccentricity": 4.0,
            "group": 1,
            "Closeness": 2.432098765432099,
            "size": 10.0
        }, {
            "label": "gene",
            "id": 31,
            "Betweenness": 127.30750889421341,
            "Out-Degree": 8,
            "Degree": 18,
            "In-Degree": 10,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.9135802469135803,
            "size": 10.0
        }, {
            "label": "genotype-phenotype",
            "id": 32,
            "Betweenness": 81.4064179799636,
            "Out-Degree": 7,
            "Degree": 12,
            "In-Degree": 5,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.814814814814815,
            "size": 10.0
        }, {
            "label": "genrel-early",
            "id": 33,
            "Betweenness": 263.6446380441829,
            "Out-Degree": 6,
            "Degree": 12,
            "In-Degree": 6,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 4.839506172839506,
            "size": 10.0
        }, {
            "label": "geometry-19th",
            "id": 34,
            "Betweenness": 20.491666666666667,
            "Out-Degree": 2,
            "Degree": 10,
            "In-Degree": 8,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.320987654320987,
            "size": 10.0
        }, {
            "label": "geometry-finitism",
            "id": 35,
            "Betweenness": 0.0,
            "Out-Degree": 3,
            "Degree": 3,
            "In-Degree": 0,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.146341463414634,
            "size": 10.0
        }, {
            "label": "heredity",
            "id": 36,
            "Betweenness": 231.30925297606214,
            "Out-Degree": 7,
            "Degree": 16,
            "In-Degree": 9,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.7901234567901234,
            "size": 10.0
        }, {
            "label": "hermann-helmholtz",
            "id": 37,
            "Betweenness": 16.02930402930403,
            "Out-Degree": 2,
            "Degree": 5,
            "In-Degree": 3,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.109756097560975,
            "size": 10.0
        }, {
            "label": "holes",
            "id": 38,
            "Betweenness": 0.0,
            "Out-Degree": 2,
            "Degree": 2,
            "In-Degree": 0,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.190476190476191,
            "size": 10.0
        }, {
            "label": "human-genome",
            "id": 39,
            "Betweenness": 6.9784752284752285,
            "Out-Degree": 6,
            "Degree": 9,
            "In-Degree": 3,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.2222222222222223,
            "size": 10.0
        }, {
            "label": "information-biological",
            "id": 40,
            "Betweenness": 33.19453879453879,
            "Out-Degree": 4,
            "Degree": 12,
            "In-Degree": 8,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.6049382716049383,
            "size": 10.0
        }, {
            "label": "information-entropy",
            "id": 41,
            "Betweenness": 0.0,
            "Out-Degree": 2,
            "Degree": 2,
            "In-Degree": 0,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 4.817073170731708,
            "size": 10.0
        }, {
            "label": "inheritance-systems",
            "id": 42,
            "Betweenness": 0.0,
            "Out-Degree": 4,
            "Degree": 5,
            "In-Degree": 1,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.382716049382716,
            "size": 10.0
        }, {
            "label": "kochen-specker",
            "id": 43,
            "Betweenness": 11.774555707450444,
            "Out-Degree": 4,
            "Degree": 11,
            "In-Degree": 7,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.037037037037037,
            "size": 10.0
        }, {
            "label": "life",
            "id": 44,
            "Betweenness": 351.365045664572,
            "Out-Degree": 5,
            "Degree": 12,
            "In-Degree": 7,
            "Eccentricity": 4.0,
            "group": 1,
            "Closeness": 2.654320987654321,
            "size": 10.0
        }, {
            "label": "models-science",
            "id": 45,
            "Betweenness": 2.2568034552713545,
            "Out-Degree": 1,
            "Degree": 6,
            "In-Degree": 5,
            "Eccentricity": 10.0,
            "group": 1,
            "Closeness": 6.1234567901234565,
            "size": 10.0
        }, {
            "label": "molecular-biology",
            "id": 46,
            "Betweenness": 296.57897182459993,
            "Out-Degree": 12,
            "Degree": 20,
            "In-Degree": 8,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.6296296296296298,
            "size": 10.0
        }, {
            "label": "molecular-genetics",
            "id": 47,
            "Betweenness": 177.81472146478617,
            "Out-Degree": 5,
            "Degree": 13,
            "In-Degree": 8,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.123456790123457,
            "size": 10.0
        }, {
            "label": "morality-biology",
            "id": 48,
            "Betweenness": 6.983333333333333,
            "Out-Degree": 5,
            "Degree": 7,
            "In-Degree": 2,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.654320987654321,
            "size": 10.0
        }, {
            "label": "paradox-simpson",
            "id": 49,
            "Betweenness": 0.0,
            "Out-Degree": 2,
            "Degree": 3,
            "In-Degree": 1,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.160493827160494,
            "size": 10.0
        }, {
            "label": "physics-holism",
            "id": 50,
            "Betweenness": 773.061027438401,
            "Out-Degree": 9,
            "Degree": 15,
            "In-Degree": 6,
            "Eccentricity": 7.0,
            "group": 3,
            "Closeness": 3.691358024691358,
            "size": 10.0
        }, {
            "label": "physics-interrelate",
            "id": 51,
            "Betweenness": 2518.3753352558056,
            "Out-Degree": 3,
            "Degree": 11,
            "In-Degree": 8,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.3950617283950617,
            "size": 10.0
        }, {
            "label": "physics-Rpcc",
            "id": 52,
            "Betweenness": 145.33495048683838,
            "Out-Degree": 5,
            "Degree": 11,
            "In-Degree": 6,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 4.802469135802469,
            "size": 10.0
        }, {
            "label": "poincare",
            "id": 53,
            "Betweenness": 110.17063492063494,
            "Out-Degree": 8,
            "Degree": 10,
            "In-Degree": 2,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 3.7023809523809526,
            "size": 10.0
        }, {
            "label": "population-genetics",
            "id": 54,
            "Betweenness": 62.76318682013459,
            "Out-Degree": 5,
            "Degree": 10,
            "In-Degree": 5,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.0,
            "size": 10.0
        }, {
            "label": "psychiatry",
            "id": 55,
            "Betweenness": 0.0,
            "Out-Degree": 3,
            "Degree": 3,
            "In-Degree": 0,
            "Eccentricity": 10.0,
            "group": 1,
            "Closeness": 6.036585365853658,
            "size": 10.0
        }, {
            "label": "qm",
            "id": 56,
            "Betweenness": 532.2035713606497,
            "Out-Degree": 9,
            "Degree": 36,
            "In-Degree": 27,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.382716049382716,
            "size": 10.0
        }, {
            "label": "qm-action-distance",
            "id": 57,
            "Betweenness": 99.73175344433838,
            "Out-Degree": 12,
            "Degree": 17,
            "In-Degree": 5,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.246913580246914,
            "size": 10.0
        }, {
            "label": "qm-bohm",
            "id": 58,
            "Betweenness": 487.2342500878758,
            "Out-Degree": 15,
            "Degree": 31,
            "In-Degree": 16,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.1234567901234565,
            "size": 10.0
        }, {
            "label": "qm-collapse",
            "id": 59,
            "Betweenness": 13.814367999150608,
            "Out-Degree": 3,
            "Degree": 11,
            "In-Degree": 8,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.049382716049383,
            "size": 10.0
        }, {
            "label": "qm-consistent-histories",
            "id": 60,
            "Betweenness": 0.0,
            "Out-Degree": 5,
            "Degree": 5,
            "In-Degree": 0,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.426829268292683,
            "size": 10.0
        }, {
            "label": "qm-copenhagen",
            "id": 61,
            "Betweenness": 7.74692972061147,
            "Out-Degree": 3,
            "Degree": 13,
            "In-Degree": 10,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.08641975308642,
            "size": 10.0
        }, {
            "label": "qm-decoherence",
            "id": 62,
            "Betweenness": 886.9248993808736,
            "Out-Degree": 15,
            "Degree": 25,
            "In-Degree": 10,
            "Eccentricity": 7.0,
            "group": 3,
            "Closeness": 3.691358024691358,
            "size": 10.0
        }, {
            "label": "qm-everett",
            "id": 63,
            "Betweenness": 11.934956767029473,
            "Out-Degree": 6,
            "Degree": 16,
            "In-Degree": 10,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 4.9753086419753085,
            "size": 10.0
        }, {
            "label": "qm-manyworlds",
            "id": 64,
            "Betweenness": 147.53634901601183,
            "Out-Degree": 13,
            "Degree": 22,
            "In-Degree": 9,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.271604938271605,
            "size": 10.0
        }, {
            "label": "qm-modal",
            "id": 65,
            "Betweenness": 63.142678472461704,
            "Out-Degree": 9,
            "Degree": 19,
            "In-Degree": 10,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.382716049382716,
            "size": 10.0
        }, {
            "label": "qm-relational",
            "id": 66,
            "Betweenness": 23.50809366072524,
            "Out-Degree": 8,
            "Degree": 12,
            "In-Degree": 4,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.0,
            "size": 10.0
        }, {
            "label": "qt-consciousness",
            "id": 67,
            "Betweenness": 0.0,
            "Out-Degree": 4,
            "Degree": 4,
            "In-Degree": 0,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.585365853658536,
            "size": 10.0
        }, {
            "label": "qt-entangle",
            "id": 68,
            "Betweenness": 129.1074730969169,
            "Out-Degree": 8,
            "Degree": 15,
            "In-Degree": 7,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 4.814814814814815,
            "size": 10.0
        }, {
            "label": "qt-epr",
            "id": 69,
            "Betweenness": 341.23494275009364,
            "Out-Degree": 11,
            "Degree": 25,
            "In-Degree": 14,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.197530864197531,
            "size": 10.0
        }, {
            "label": "qt-idind",
            "id": 70,
            "Betweenness": 40.77195392491012,
            "Out-Degree": 2,
            "Degree": 6,
            "In-Degree": 4,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.530864197530864,
            "size": 10.0
        }, {
            "label": "qt-measurement",
            "id": 71,
            "Betweenness": 329.7994159679912,
            "Out-Degree": 11,
            "Degree": 27,
            "In-Degree": 16,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.296296296296297,
            "size": 10.0
        }, {
            "label": "qt-nvd",
            "id": 72,
            "Betweenness": 33.60210783368678,
            "Out-Degree": 5,
            "Degree": 6,
            "In-Degree": 1,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.432098765432099,
            "size": 10.0
        }, {
            "label": "qt-quantcomp",
            "id": 73,
            "Betweenness": 16.11620879120879,
            "Out-Degree": 7,
            "Degree": 9,
            "In-Degree": 2,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.3580246913580245,
            "size": 10.0
        }, {
            "label": "qt-quantlog",
            "id": 74,
            "Betweenness": 100.87063492063493,
            "Out-Degree": 3,
            "Degree": 9,
            "In-Degree": 6,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.271604938271605,
            "size": 10.0
        }, {
            "label": "qt-uncertainty",
            "id": 75,
            "Betweenness": 12.49356476341524,
            "Out-Degree": 3,
            "Degree": 12,
            "In-Degree": 9,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 5.049382716049383,
            "size": 10.0
        }, {
            "label": "quantum-field-theory",
            "id": 76,
            "Betweenness": 175.68028031075013,
            "Out-Degree": 4,
            "Degree": 9,
            "In-Degree": 5,
            "Eccentricity": 8.0,
            "group": 3,
            "Closeness": 4.506172839506172,
            "size": 10.0
        }, {
            "label": "quantum-gravity",
            "id": 77,
            "Betweenness": 281.63118817102645,
            "Out-Degree": 8,
            "Degree": 13,
            "In-Degree": 5,
            "Eccentricity": 7.0,
            "group": 3,
            "Closeness": 3.8395061728395063,
            "size": 10.0
        }, {
            "label": "reduction-biology",
            "id": 78,
            "Betweenness": 2346.52845202201,
            "Out-Degree": 14,
            "Degree": 20,
            "In-Degree": 6,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.567901234567901,
            "size": 10.0
        }, {
            "label": "reichenbach",
            "id": 79,
            "Betweenness": 230.6385973135242,
            "Out-Degree": 6,
            "Degree": 12,
            "In-Degree": 6,
            "Eccentricity": 9.0,
            "group": 3,
            "Closeness": 4.888888888888889,
            "size": 10.0
        }, {
            "label": "replication",
            "id": 80,
            "Betweenness": 185.95713113565932,
            "Out-Degree": 11,
            "Degree": 16,
            "In-Degree": 5,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.765432098765432,
            "size": 10.0
        }, {
            "label": "schlick",
            "id": 81,
            "Betweenness": 0.0,
            "Out-Degree": 6,
            "Degree": 6,
            "In-Degree": 0,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.211764705882353,
            "size": 10.0
        }, {
            "label": "scientific-explanation",
            "id": 82,
            "Betweenness": 270.4153139769408,
            "Out-Degree": 1,
            "Degree": 11,
            "In-Degree": 10,
            "Eccentricity": 9.0,
            "group": 1,
            "Closeness": 5.209876543209877,
            "size": 10.0
        }, {
            "label": "scientific-reduction",
            "id": 83,
            "Betweenness": 2227.027777777778,
            "Out-Degree": 3,
            "Degree": 4,
            "In-Degree": 1,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.197530864197531,
            "size": 10.0
        }, {
            "label": "selection-units",
            "id": 84,
            "Betweenness": 209.60808420003033,
            "Out-Degree": 7,
            "Degree": 18,
            "In-Degree": 11,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 2.8518518518518516,
            "size": 10.0
        }, {
            "label": "sociobiology",
            "id": 85,
            "Betweenness": 217.1809523809522,
            "Out-Degree": 4,
            "Degree": 11,
            "In-Degree": 7,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.493827160493827,
            "size": 10.0
        }, {
            "label": "spacetime-convensimul",
            "id": 86,
            "Betweenness": 24.650066247821666,
            "Out-Degree": 2,
            "Degree": 7,
            "In-Degree": 5,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 4.9753086419753085,
            "size": 10.0
        }, {
            "label": "spacetime-holearg",
            "id": 87,
            "Betweenness": 578.7629153660871,
            "Out-Degree": 6,
            "Degree": 17,
            "In-Degree": 11,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.345679012345679,
            "size": 10.0
        }, {
            "label": "spacetime-iframes",
            "id": 88,
            "Betweenness": 104.03582144043175,
            "Out-Degree": 5,
            "Degree": 11,
            "In-Degree": 6,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 4.9753086419753085,
            "size": 10.0
        }, {
            "label": "spacetime-singularities",
            "id": 89,
            "Betweenness": 13.199999999999998,
            "Out-Degree": 3,
            "Degree": 4,
            "In-Degree": 1,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.686746987951807,
            "size": 10.0
        }, {
            "label": "spacetime-supertasks",
            "id": 90,
            "Betweenness": 15.291666666666666,
            "Out-Degree": 1,
            "Degree": 4,
            "In-Degree": 3,
            "Eccentricity": 8.0,
            "group": 2,
            "Closeness": 4.851851851851852,
            "size": 10.0
        }, {
            "label": "spacetime-theories",
            "id": 91,
            "Betweenness": 36.552580047321925,
            "Out-Degree": 3,
            "Degree": 5,
            "In-Degree": 2,
            "Eccentricity": 9.0,
            "group": 2,
            "Closeness": 5.135802469135802,
            "size": 10.0
        }, {
            "label": "species",
            "id": 92,
            "Betweenness": 94.72293603578233,
            "Out-Degree": 2,
            "Degree": 8,
            "In-Degree": 6,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.345679012345679,
            "size": 10.0
        }, {
            "label": "spencer",
            "id": 93,
            "Betweenness": 22.6038851123576,
            "Out-Degree": 3,
            "Degree": 6,
            "In-Degree": 3,
            "Eccentricity": 5.0,
            "group": 1,
            "Closeness": 3.2222222222222223,
            "size": 10.0
        }, {
            "label": "statphys-Boltzmann",
            "id": 94,
            "Betweenness": 214.4873015873016,
            "Out-Degree": 3,
            "Degree": 7,
            "In-Degree": 4,
            "Eccentricity": 6.0,
            "group": 2,
            "Closeness": 3.876543209876543,
            "size": 10.0
        }, {
            "label": "statphys-statmech",
            "id": 95,
            "Betweenness": 1186.8827760202757,
            "Out-Degree": 2,
            "Degree": 11,
            "In-Degree": 9,
            "Eccentricity": 6.0,
            "group": 2,
            "Closeness": 4.1234567901234565,
            "size": 10.0
        }, {
            "label": "symmetry-breaking",
            "id": 96,
            "Betweenness": 189.25678300501247,
            "Out-Degree": 5,
            "Degree": 9,
            "In-Degree": 4,
            "Eccentricity": 7.0,
            "group": 3,
            "Closeness": 3.9135802469135803,
            "size": 10.0
        }, {
            "label": "teleology-biology",
            "id": 97,
            "Betweenness": 82.50048206991067,
            "Out-Degree": 1,
            "Degree": 11,
            "In-Degree": 10,
            "Eccentricity": 6.0,
            "group": 1,
            "Closeness": 3.2222222222222223,
            "size": 10.0
        }, {
            "label": "time-machine",
            "id": 98,
            "Betweenness": 56.18353174603175,
            "Out-Degree": 3,
            "Degree": 4,
            "In-Degree": 1,
            "Eccentricity": 7.0,
            "group": 2,
            "Closeness": 4.097560975609756,
            "size": 10.0
        }, {
            "label": "time-thermo",
            "id": 99,
            "Betweenness": 1122.3989343989347,
            "Out-Degree": 3,
            "Degree": 8,
            "In-Degree": 5,
            "Eccentricity": 6.0,
            "group": 2,
            "Closeness": 4.08641975308642,
            "size": 10.0
        }, {
            "label": "evolution",
            "id": 100,
            "Betweenness": 0.0,
            "Out-Degree": 0,
            "Degree": 0,
            "In-Degree": 0,
            "Eccentricity": 0.0,
            "group": 1,
            "Closeness": 0.0,
            "size": 10.0
        }],
            "links": [{
            "source": 0,
            "target": 5
        }, {
            "source": 0,
            "target": 15
        }, {
            "source": 0,
            "target": 25
        }, {
            "source": 0,
            "target": 26
        }, {
            "source": 0,
            "target": 31
        }, {
            "source": 0,
            "target": 44
        }, {
            "source": 0,
            "target": 46
        }, {
            "source": 0,
            "target": 47
        }, {
            "source": 0,
            "target": 53
        }, {
            "source": 0,
            "target": 83
        }, {
            "source": 0,
            "target": 84
        }, {
            "source": 0,
            "target": 99
        }, {
            "source": 1,
            "target": 83
        }, {
            "source": 1,
            "target": 84
        }, {
            "source": 2,
            "target": 42
        }, {
            "source": 2,
            "target": 55
        }, {
            "source": 2,
            "target": 57
        }, {
            "source": 2,
            "target": 68
        }, {
            "source": 3,
            "target": 91
        }, {
            "source": 4,
            "target": 1
        }, {
            "source": 4,
            "target": 3
        }, {
            "source": 4,
            "target": 6
        }, {
            "source": 4,
            "target": 15
        }, {
            "source": 4,
            "target": 25
        }, {
            "source": 4,
            "target": 30
        }, {
            "source": 4,
            "target": 43
        }, {
            "source": 4,
            "target": 79
        }, {
            "source": 4,
            "target": 83
        }, {
            "source": 4,
            "target": 84
        }, {
            "source": 4,
            "target": 91
        }, {
            "source": 4,
            "target": 99
        }, {
            "source": 5,
            "target": 0
        }, {
            "source": 5,
            "target": 1
        }, {
            "source": 5,
            "target": 3
        }, {
            "source": 5,
            "target": 4
        }, {
            "source": 5,
            "target": 5
        }, {
            "source": 5,
            "target": 6
        }, {
            "source": 5,
            "target": 13
        }, {
            "source": 5,
            "target": 14
        }, {
            "source": 5,
            "target": 15
        }, {
            "source": 5,
            "target": 17
        }, {
            "source": 5,
            "target": 19
        }, {
            "source": 5,
            "target": 25
        }, {
            "source": 5,
            "target": 26
        }, {
            "source": 5,
            "target": 27
        }, {
            "source": 5,
            "target": 29
        }, {
            "source": 5,
            "target": 30
        }, {
            "source": 5,
            "target": 31
        }, {
            "source": 5,
            "target": 35
        }, {
            "source": 5,
            "target": 38
        }, {
            "source": 5,
            "target": 39
        }, {
            "source": 5,
            "target": 43
        }, {
            "source": 5,
            "target": 45
        }, {
            "source": 5,
            "target": 46
        }, {
            "source": 5,
            "target": 53
        }, {
            "source": 5,
            "target": 77
        }, {
            "source": 5,
            "target": 79
        }, {
            "source": 5,
            "target": 83
        }, {
            "source": 5,
            "target": 84
        }, {
            "source": 5,
            "target": 91
        }, {
            "source": 5,
            "target": 96
        }, {
            "source": 5,
            "target": 99
        }, {
            "source": 6,
            "target": 4
        }, {
            "source": 6,
            "target": 5
        }, {
            "source": 7,
            "target": 50
        }, {
            "source": 7,
            "target": 60
        }, {
            "source": 7,
            "target": 61
        }, {
            "source": 7,
            "target": 68
        }, {
            "source": 7,
            "target": 74
        }, {
            "source": 8,
            "target": 9
        }, {
            "source": 9,
            "target": 8
        }, {
            "source": 9,
            "target": 16
        }, {
            "source": 9,
            "target": 48
        }, {
            "source": 9,
            "target": 51
        }, {
            "source": 9,
            "target": 55
        }, {
            "source": 9,
            "target": 56
        }, {
            "source": 9,
            "target": 68
        }, {
            "source": 9,
            "target": 78
        }, {
            "source": 9,
            "target": 81
        }, {
            "source": 10,
            "target": 2
        }, {
            "source": 10,
            "target": 11
        }, {
            "source": 10,
            "target": 16
        }, {
            "source": 10,
            "target": 94
        }, {
            "source": 10,
            "target": 98
        }, {
            "source": 11,
            "target": 16
        }, {
            "source": 11,
            "target": 44
        }, {
            "source": 11,
            "target": 55
        }, {
            "source": 11,
            "target": 70
        }, {
            "source": 11,
            "target": 81
        }, {
            "source": 11,
            "target": 85
        }, {
            "source": 12,
            "target": 44
        }, {
            "source": 12,
            "target": 50
        }, {
            "source": 12,
            "target": 69
        }, {
            "source": 12,
            "target": 77
        }, {
            "source": 12,
            "target": 81
        }, {
            "source": 13,
            "target": 3
        }, {
            "source": 13,
            "target": 17
        }, {
            "source": 13,
            "target": 25
        }, {
            "source": 14,
            "target": 15
        }, {
            "source": 14,
            "target": 96
        }, {
            "source": 15,
            "target": 0
        }, {
            "source": 15,
            "target": 5
        }, {
            "source": 15,
            "target": 14
        }, {
            "source": 15,
            "target": 29
        }, {
            "source": 15,
            "target": 81
        }, {
            "source": 15,
            "target": 83
        }, {
            "source": 15,
            "target": 91
        }, {
            "source": 15,
            "target": 96
        }, {
            "source": 15,
            "target": 99
        }, {
            "source": 16,
            "target": 55
        }, {
            "source": 16,
            "target": 57
        }, {
            "source": 16,
            "target": 70
        }, {
            "source": 16,
            "target": 86
        }, {
            "source": 16,
            "target": 89
        }, {
            "source": 16,
            "target": 98
        }, {
            "source": 17,
            "target": 3
        }, {
            "source": 17,
            "target": 5
        }, {
            "source": 17,
            "target": 13
        }, {
            "source": 17,
            "target": 77
        }, {
            "source": 18,
            "target": 22
        }, {
            "source": 18,
            "target": 32
        }, {
            "source": 18,
            "target": 33
        }, {
            "source": 18,
            "target": 49
        }, {
            "source": 18,
            "target": 60
        }, {
            "source": 18,
            "target": 68
        }, {
            "source": 18,
            "target": 70
        }, {
            "source": 18,
            "target": 74
        }, {
            "source": 18,
            "target": 85
        }, {
            "source": 18,
            "target": 86
        }, {
            "source": 18,
            "target": 87
        }, {
            "source": 18,
            "target": 90
        }, {
            "source": 19,
            "target": 6
        }, {
            "source": 19,
            "target": 30
        }, {
            "source": 19,
            "target": 43
        }, {
            "source": 19,
            "target": 99
        }, {
            "source": 20,
            "target": 39
        }, {
            "source": 20,
            "target": 96
        }, {
            "source": 21,
            "target": 33
        }, {
            "source": 21,
            "target": 36
        }, {
            "source": 21,
            "target": 52
        }, {
            "source": 22,
            "target": 18
        }, {
            "source": 22,
            "target": 87
        }, {
            "source": 23,
            "target": 93
        }, {
            "source": 24,
            "target": 18
        }, {
            "source": 24,
            "target": 32
        }, {
            "source": 24,
            "target": 87
        }, {
            "source": 24,
            "target": 90
        }, {
            "source": 25,
            "target": 46
        }, {
            "source": 25,
            "target": 53
        }, {
            "source": 26,
            "target": 0
        }, {
            "source": 26,
            "target": 5
        }, {
            "source": 27,
            "target": 15
        }, {
            "source": 27,
            "target": 20
        }, {
            "source": 27,
            "target": 26
        }, {
            "source": 27,
            "target": 35
        }, {
            "source": 27,
            "target": 79
        }, {
            "source": 27,
            "target": 92
        }, {
            "source": 27,
            "target": 99
        }, {
            "source": 28,
            "target": 0
        }, {
            "source": 28,
            "target": 1
        }, {
            "source": 28,
            "target": 5
        }, {
            "source": 28,
            "target": 14
        }, {
            "source": 28,
            "target": 15
        }, {
            "source": 28,
            "target": 25
        }, {
            "source": 28,
            "target": 29
        }, {
            "source": 28,
            "target": 43
        }, {
            "source": 28,
            "target": 47
        }, {
            "source": 28,
            "target": 83
        }, {
            "source": 28,
            "target": 91
        }, {
            "source": 28,
            "target": 92
        }, {
            "source": 28,
            "target": 96
        }, {
            "source": 29,
            "target": 0
        }, {
            "source": 29,
            "target": 5
        }, {
            "source": 29,
            "target": 9
        }, {
            "source": 29,
            "target": 15
        }, {
            "source": 29,
            "target": 25
        }, {
            "source": 29,
            "target": 53
        }, {
            "source": 29,
            "target": 96
        }, {
            "source": 29,
            "target": 99
        }, {
            "source": 30,
            "target": 35
        }, {
            "source": 30,
            "target": 39
        }, {
            "source": 30,
            "target": 45
        }, {
            "source": 30,
            "target": 46
        }, {
            "source": 30,
            "target": 53
        }, {
            "source": 30,
            "target": 83
        }, {
            "source": 30,
            "target": 96
        }, {
            "source": 30,
            "target": 99
        }, {
            "source": 31,
            "target": 5
        }, {
            "source": 31,
            "target": 15
        }, {
            "source": 31,
            "target": 30
        }, {
            "source": 31,
            "target": 39
        }, {
            "source": 31,
            "target": 45
        }, {
            "source": 31,
            "target": 83
        }, {
            "source": 31,
            "target": 99
        }, {
            "source": 32,
            "target": 18
        }, {
            "source": 32,
            "target": 22
        }, {
            "source": 32,
            "target": 33
        }, {
            "source": 32,
            "target": 78
        }, {
            "source": 32,
            "target": 85
        }, {
            "source": 32,
            "target": 86
        }, {
            "source": 33,
            "target": 33
        }, {
            "source": 33,
            "target": 86
        }, {
            "source": 34,
            "target": 33
        }, {
            "source": 34,
            "target": 55
        }, {
            "source": 34,
            "target": 89
        }, {
            "source": 35,
            "target": 0
        }, {
            "source": 35,
            "target": 1
        }, {
            "source": 35,
            "target": 5
        }, {
            "source": 35,
            "target": 38
        }, {
            "source": 35,
            "target": 39
        }, {
            "source": 35,
            "target": 45
        }, {
            "source": 35,
            "target": 99
        }, {
            "source": 36,
            "target": 33
        }, {
            "source": 36,
            "target": 70
        }, {
            "source": 37,
            "target": 86
        }, {
            "source": 37,
            "target": 88
        }, {
            "source": 38,
            "target": 19
        }, {
            "source": 38,
            "target": 30
        }, {
            "source": 38,
            "target": 45
        }, {
            "source": 38,
            "target": 46
        }, {
            "source": 38,
            "target": 77
        }, {
            "source": 38,
            "target": 91
        }, {
            "source": 39,
            "target": 25
        }, {
            "source": 39,
            "target": 31
        }, {
            "source": 39,
            "target": 35
        }, {
            "source": 39,
            "target": 96
        }, {
            "source": 40,
            "target": 93
        }, {
            "source": 40,
            "target": 94
        }, {
            "source": 41,
            "target": 27
        }, {
            "source": 41,
            "target": 35
        }, {
            "source": 41,
            "target": 39
        }, {
            "source": 41,
            "target": 79
        }, {
            "source": 42,
            "target": 55
        }, {
            "source": 42,
            "target": 57
        }, {
            "source": 42,
            "target": 64
        }, {
            "source": 42,
            "target": 70
        }, {
            "source": 43,
            "target": 15
        }, {
            "source": 43,
            "target": 45
        }, {
            "source": 43,
            "target": 49
        }, {
            "source": 43,
            "target": 94
        }, {
            "source": 43,
            "target": 96
        }, {
            "source": 44,
            "target": 81
        }, {
            "source": 45,
            "target": 5
        }, {
            "source": 45,
            "target": 6
        }, {
            "source": 45,
            "target": 8
        }, {
            "source": 45,
            "target": 12
        }, {
            "source": 45,
            "target": 30
        }, {
            "source": 45,
            "target": 35
        }, {
            "source": 45,
            "target": 38
        }, {
            "source": 45,
            "target": 39
        }, {
            "source": 45,
            "target": 43
        }, {
            "source": 45,
            "target": 46
        }, {
            "source": 45,
            "target": 77
        }, {
            "source": 45,
            "target": 81
        }, {
            "source": 46,
            "target": 8
        }, {
            "source": 46,
            "target": 25
        }, {
            "source": 46,
            "target": 30
        }, {
            "source": 46,
            "target": 31
        }, {
            "source": 46,
            "target": 50
        }, {
            "source": 47,
            "target": 1
        }, {
            "source": 47,
            "target": 26
        }, {
            "source": 47,
            "target": 27
        }, {
            "source": 47,
            "target": 84
        }, {
            "source": 47,
            "target": 92
        }, {
            "source": 48,
            "target": 9
        }, {
            "source": 48,
            "target": 51
        }, {
            "source": 49,
            "target": 2
        }, {
            "source": 49,
            "target": 18
        }, {
            "source": 49,
            "target": 51
        }, {
            "source": 49,
            "target": 55
        }, {
            "source": 49,
            "target": 56
        }, {
            "source": 49,
            "target": 57
        }, {
            "source": 49,
            "target": 64
        }, {
            "source": 49,
            "target": 67
        }, {
            "source": 49,
            "target": 94
        }, {
            "source": 50,
            "target": 75
        }, {
            "source": 50,
            "target": 81
        }, {
            "source": 50,
            "target": 82
        }, {
            "source": 51,
            "target": 2
        }, {
            "source": 51,
            "target": 9
        }, {
            "source": 51,
            "target": 55
        }, {
            "source": 51,
            "target": 57
        }, {
            "source": 51,
            "target": 78
        }, {
            "source": 52,
            "target": 11
        }, {
            "source": 52,
            "target": 18
        }, {
            "source": 52,
            "target": 33
        }, {
            "source": 52,
            "target": 36
        }, {
            "source": 52,
            "target": 78
        }, {
            "source": 52,
            "target": 85
        }, {
            "source": 52,
            "target": 94
        }, {
            "source": 52,
            "target": 95
        }, {
            "source": 53,
            "target": 25
        }, {
            "source": 53,
            "target": 29
        }, {
            "source": 53,
            "target": 46
        }, {
            "source": 53,
            "target": 83
        }, {
            "source": 53,
            "target": 99
        }, {
            "source": 54,
            "target": 8
        }, {
            "source": 54,
            "target": 44
        }, {
            "source": 54,
            "target": 81
        }, {
            "source": 55,
            "target": 42
        }, {
            "source": 55,
            "target": 57
        }, {
            "source": 55,
            "target": 58
        }, {
            "source": 55,
            "target": 60
        }, {
            "source": 55,
            "target": 61
        }, {
            "source": 55,
            "target": 62
        }, {
            "source": 55,
            "target": 63
        }, {
            "source": 55,
            "target": 64
        }, {
            "source": 55,
            "target": 65
        }, {
            "source": 56,
            "target": 2
        }, {
            "source": 56,
            "target": 42
        }, {
            "source": 56,
            "target": 49
        }, {
            "source": 56,
            "target": 51
        }, {
            "source": 56,
            "target": 55
        }, {
            "source": 56,
            "target": 57
        }, {
            "source": 56,
            "target": 58
        }, {
            "source": 56,
            "target": 62
        }, {
            "source": 56,
            "target": 63
        }, {
            "source": 56,
            "target": 64
        }, {
            "source": 56,
            "target": 68
        }, {
            "source": 56,
            "target": 74
        }, {
            "source": 57,
            "target": 2
        }, {
            "source": 57,
            "target": 18
        }, {
            "source": 57,
            "target": 42
        }, {
            "source": 57,
            "target": 49
        }, {
            "source": 57,
            "target": 55
        }, {
            "source": 57,
            "target": 60
        }, {
            "source": 57,
            "target": 61
        }, {
            "source": 57,
            "target": 63
        }, {
            "source": 57,
            "target": 64
        }, {
            "source": 57,
            "target": 67
        }, {
            "source": 57,
            "target": 68
        }, {
            "source": 57,
            "target": 70
        }, {
            "source": 57,
            "target": 73
        }, {
            "source": 57,
            "target": 74
        }, {
            "source": 57,
            "target": 76
        }, {
            "source": 58,
            "target": 2
        }, {
            "source": 58,
            "target": 55
        }, {
            "source": 58,
            "target": 57
        }, {
            "source": 59,
            "target": 2
        }, {
            "source": 59,
            "target": 61
        }, {
            "source": 59,
            "target": 68
        }, {
            "source": 59,
            "target": 70
        }, {
            "source": 59,
            "target": 73
        }, {
            "source": 60,
            "target": 55
        }, {
            "source": 60,
            "target": 68
        }, {
            "source": 60,
            "target": 74
        }, {
            "source": 61,
            "target": 55
        }, {
            "source": 61,
            "target": 57
        }, {
            "source": 61,
            "target": 58
        }, {
            "source": 61,
            "target": 60
        }, {
            "source": 61,
            "target": 62
        }, {
            "source": 61,
            "target": 63
        }, {
            "source": 61,
            "target": 64
        }, {
            "source": 61,
            "target": 67
        }, {
            "source": 61,
            "target": 68
        }, {
            "source": 61,
            "target": 70
        }, {
            "source": 61,
            "target": 74
        }, {
            "source": 61,
            "target": 75
        }, {
            "source": 61,
            "target": 76
        }, {
            "source": 61,
            "target": 94
        }, {
            "source": 61,
            "target": 98
        }, {
            "source": 62,
            "target": 55
        }, {
            "source": 62,
            "target": 57
        }, {
            "source": 62,
            "target": 63
        }, {
            "source": 62,
            "target": 64
        }, {
            "source": 62,
            "target": 65
        }, {
            "source": 62,
            "target": 70
        }, {
            "source": 63,
            "target": 55
        }, {
            "source": 63,
            "target": 56
        }, {
            "source": 63,
            "target": 57
        }, {
            "source": 63,
            "target": 58
        }, {
            "source": 63,
            "target": 60
        }, {
            "source": 63,
            "target": 61
        }, {
            "source": 63,
            "target": 62
        }, {
            "source": 63,
            "target": 65
        }, {
            "source": 63,
            "target": 67
        }, {
            "source": 63,
            "target": 68
        }, {
            "source": 63,
            "target": 69
        }, {
            "source": 63,
            "target": 70
        }, {
            "source": 63,
            "target": 72
        }, {
            "source": 64,
            "target": 42
        }, {
            "source": 64,
            "target": 55
        }, {
            "source": 64,
            "target": 57
        }, {
            "source": 64,
            "target": 61
        }, {
            "source": 64,
            "target": 62
        }, {
            "source": 64,
            "target": 63
        }, {
            "source": 64,
            "target": 65
        }, {
            "source": 64,
            "target": 68
        }, {
            "source": 64,
            "target": 70
        }, {
            "source": 65,
            "target": 55
        }, {
            "source": 65,
            "target": 56
        }, {
            "source": 65,
            "target": 58
        }, {
            "source": 65,
            "target": 62
        }, {
            "source": 65,
            "target": 64
        }, {
            "source": 65,
            "target": 67
        }, {
            "source": 65,
            "target": 70
        }, {
            "source": 65,
            "target": 73
        }, {
            "source": 66,
            "target": 58
        }, {
            "source": 66,
            "target": 75
        }, {
            "source": 66,
            "target": 76
        }, {
            "source": 66,
            "target": 95
        }, {
            "source": 67,
            "target": 2
        }, {
            "source": 67,
            "target": 51
        }, {
            "source": 67,
            "target": 60
        }, {
            "source": 67,
            "target": 62
        }, {
            "source": 67,
            "target": 63
        }, {
            "source": 67,
            "target": 68
        }, {
            "source": 67,
            "target": 72
        }, {
            "source": 67,
            "target": 73
        }, {
            "source": 68,
            "target": 2
        }, {
            "source": 68,
            "target": 18
        }, {
            "source": 68,
            "target": 56
        }, {
            "source": 68,
            "target": 57
        }, {
            "source": 68,
            "target": 60
        }, {
            "source": 68,
            "target": 61
        }, {
            "source": 68,
            "target": 62
        }, {
            "source": 68,
            "target": 64
        }, {
            "source": 68,
            "target": 67
        }, {
            "source": 68,
            "target": 70
        }, {
            "source": 68,
            "target": 74
        }, {
            "source": 69,
            "target": 49
        }, {
            "source": 69,
            "target": 55
        }, {
            "source": 70,
            "target": 49
        }, {
            "source": 70,
            "target": 55
        }, {
            "source": 70,
            "target": 57
        }, {
            "source": 70,
            "target": 58
        }, {
            "source": 70,
            "target": 60
        }, {
            "source": 70,
            "target": 61
        }, {
            "source": 70,
            "target": 62
        }, {
            "source": 70,
            "target": 63
        }, {
            "source": 70,
            "target": 64
        }, {
            "source": 70,
            "target": 68
        }, {
            "source": 70,
            "target": 74
        }, {
            "source": 71,
            "target": 55
        }, {
            "source": 71,
            "target": 57
        }, {
            "source": 71,
            "target": 61
        }, {
            "source": 71,
            "target": 73
        }, {
            "source": 71,
            "target": 75
        }, {
            "source": 72,
            "target": 2
        }, {
            "source": 72,
            "target": 55
        }, {
            "source": 72,
            "target": 58
        }, {
            "source": 72,
            "target": 61
        }, {
            "source": 72,
            "target": 67
        }, {
            "source": 72,
            "target": 68
        }, {
            "source": 72,
            "target": 70
        }, {
            "source": 73,
            "target": 42
        }, {
            "source": 73,
            "target": 55
        }, {
            "source": 73,
            "target": 71
        }, {
            "source": 74,
            "target": 55
        }, {
            "source": 74,
            "target": 57
        }, {
            "source": 74,
            "target": 60
        }, {
            "source": 75,
            "target": 55
        }, {
            "source": 75,
            "target": 69
        }, {
            "source": 75,
            "target": 76
        }, {
            "source": 75,
            "target": 95
        }, {
            "source": 76,
            "target": 55
        }, {
            "source": 76,
            "target": 62
        }, {
            "source": 76,
            "target": 63
        }, {
            "source": 76,
            "target": 70
        }, {
            "source": 76,
            "target": 74
        }, {
            "source": 76,
            "target": 75
        }, {
            "source": 76,
            "target": 86
        }, {
            "source": 76,
            "target": 94
        }, {
            "source": 77,
            "target": 4
        }, {
            "source": 77,
            "target": 5
        }, {
            "source": 77,
            "target": 19
        }, {
            "source": 77,
            "target": 30
        }, {
            "source": 77,
            "target": 35
        }, {
            "source": 77,
            "target": 43
        }, {
            "source": 77,
            "target": 44
        }, {
            "source": 77,
            "target": 45
        }, {
            "source": 77,
            "target": 46
        }, {
            "source": 77,
            "target": 50
        }, {
            "source": 77,
            "target": 81
        }, {
            "source": 77,
            "target": 83
        }, {
            "source": 77,
            "target": 84
        }, {
            "source": 77,
            "target": 96
        }, {
            "source": 78,
            "target": 9
        }, {
            "source": 78,
            "target": 42
        }, {
            "source": 78,
            "target": 51
        }, {
            "source": 78,
            "target": 55
        }, {
            "source": 78,
            "target": 70
        }, {
            "source": 78,
            "target": 73
        }, {
            "source": 79,
            "target": 5
        }, {
            "source": 79,
            "target": 19
        }, {
            "source": 79,
            "target": 27
        }, {
            "source": 79,
            "target": 30
        }, {
            "source": 79,
            "target": 31
        }, {
            "source": 79,
            "target": 35
        }, {
            "source": 79,
            "target": 39
        }, {
            "source": 79,
            "target": 41
        }, {
            "source": 79,
            "target": 43
        }, {
            "source": 79,
            "target": 45
        }, {
            "source": 79,
            "target": 83
        }, {
            "source": 80,
            "target": 18
        }, {
            "source": 80,
            "target": 24
        }, {
            "source": 80,
            "target": 32
        }, {
            "source": 80,
            "target": 36
        }, {
            "source": 80,
            "target": 52
        }, {
            "source": 80,
            "target": 78
        }, {
            "source": 81,
            "target": 9
        }, {
            "source": 82,
            "target": 50
        }, {
            "source": 82,
            "target": 77
        }, {
            "source": 82,
            "target": 81
        }, {
            "source": 83,
            "target": 1
        }, {
            "source": 83,
            "target": 4
        }, {
            "source": 83,
            "target": 5
        }, {
            "source": 83,
            "target": 25
        }, {
            "source": 83,
            "target": 30
        }, {
            "source": 83,
            "target": 79
        }, {
            "source": 83,
            "target": 99
        }, {
            "source": 84,
            "target": 0
        }, {
            "source": 84,
            "target": 26
        }, {
            "source": 84,
            "target": 27
        }, {
            "source": 84,
            "target": 35
        }, {
            "source": 85,
            "target": 18
        }, {
            "source": 85,
            "target": 78
        }, {
            "source": 86,
            "target": 16
        }, {
            "source": 86,
            "target": 18
        }, {
            "source": 86,
            "target": 32
        }, {
            "source": 86,
            "target": 76
        }, {
            "source": 86,
            "target": 89
        }, {
            "source": 86,
            "target": 95
        }, {
            "source": 87,
            "target": 18
        }, {
            "source": 87,
            "target": 32
        }, {
            "source": 87,
            "target": 33
        }, {
            "source": 87,
            "target": 85
        }, {
            "source": 87,
            "target": 86
        }, {
            "source": 88,
            "target": 86
        }, {
            "source": 88,
            "target": 87
        }, {
            "source": 88,
            "target": 97
        }, {
            "source": 89,
            "target": 16
        }, {
            "source": 90,
            "target": 32
        }, {
            "source": 90,
            "target": 86
        }, {
            "source": 90,
            "target": 87
        }, {
            "source": 91,
            "target": 4
        }, {
            "source": 91,
            "target": 99
        }, {
            "source": 92,
            "target": 15
        }, {
            "source": 92,
            "target": 84
        }, {
            "source": 92,
            "target": 99
        }, {
            "source": 93,
            "target": 24
        }, {
            "source": 93,
            "target": 50
        }, {
            "source": 93,
            "target": 94
        }, {
            "source": 94,
            "target": 50
        }, {
            "source": 94,
            "target": 93
        }, {
            "source": 95,
            "target": 55
        }, {
            "source": 95,
            "target": 69
        }, {
            "source": 95,
            "target": 86
        }, {
            "source": 95,
            "target": 87
        }, {
            "source": 95,
            "target": 98
        }, {
            "source": 96,
            "target": 5
        }, {
            "source": 97,
            "target": 16
        }, {
            "source": 97,
            "target": 86
        }, {
            "source": 97,
            "target": 98
        }, {
            "source": 98,
            "target": 50
        }, {
            "source": 98,
            "target": 93
        }, {
            "source": 98,
            "target": 94
        }]
    }
</script>
