--- ------------------------------------------------------------------------------------------------
--- This file is to be used to log any changes in the database schema. All such changes will be 
--- reviewed and moved to production. Strictly follow the format given below for the changes.  
--- Be as specific as possible while giving the reason.
--- ------------------------------------------------------------------------------------------------
--- Date: 8/18/2014
--- Reason:adding another enum review for professors not in database
--- Created by: kt
--- Module Name:user 
--- ------------------------------------------------------------------------------------------------
--- Queries
--- ------------------------------------------------------------------------------------------------
   ALTER TABLE user MODIFY COLUMN status ENUM('invited','temp','active','inactive','review');
--- ------------------------------------------------------------------------------------------------
--- Date: 
--- Reason:
--- Created by:
--- Module Name: 
--- ------------------------------------------------------------------------------------------------
--- Queries

--- ------------------------------------------------------------------------------------------------
